# Generated by Django 5.1 on 2025-11-28 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['session', 'question_index'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('initial_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('initial_feedback', models.TextField(blank=True)),
                ('final_feedback', models.TextField(blank=True)),
                ('target_followups', models.IntegerField(default=1)),
                ('completed_followups', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='chatapp.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', 'topic'], name='chatapp_ses_usernam_7448b6_idx'), models.Index(fields=['created_at'], name='chatapp_ses_created_87656f_idx')],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='chatapp.session'),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('followup_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='chatapp.answer')),
            ],
            options={
                'ordering': ['answer', 'followup_index'],
                'indexes': [models.Index(fields=['answer', 'followup_index'], name='chatapp_fol_answer__b1ca1c_idx')],
                'unique_together': {('answer', 'followup_index')},
            },
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'created_at'], name='chatapp_ans_questio_2ed5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['session', 'question_index'], name='chatapp_que_session_38b9bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('session', 'question_index')},
        ),
    ]
